#!/bin/sh

rm -f *.gcda

../compiler/obc1 -I ../lib -x ../test/xTypes.m >xTypes.k
../compiler/obc1 -I ../lib -07 ../test/xTypes07.m >xTypes07.k
../compiler/obc1 -I ../lib -x ../test/xPrelude.m >xPrelude.k

for f in ../test/t*.m; do
    echo $f
    case $f in
        tMixIt.m) flag="-w -x";;
        tNan.m) flag="-b -x";;
        *07.m) flag="-07 -x";;
        *) flag="-x";;
    esac

    ../compiler/obc1 -I ../lib $flag $f >a.k
    ../runtime/oblink -L ../lib xTypes.k xTypes07.k xPrelude.k a.k -o a.x
    ./obxj a.x dummy arguments >/dev/null 2>&1
done
