.\" Copyright (C) 1999\-2016 J. M. Spivey
.TH OBB 1
.SH NAME
obb \- Oberon\-2 browser
.SH SYNOPSIS
.B obb
[ \-I
.IR DIR ]... MODULE
.SH DESCRIPTION
.LP
.B Obb
is a browser associated with the Oxford Oberon compiler.
It finds the interface definition associated with a given module and
prints it in human-readable form.
The command-line argument is the name of the module, without any
filename extension; the definition of this module is found using the
same search method as is used when the module is imported.
.TP
.BI -I DIR
add DIR to the list of directories to be searched.

.SH AUTHOR
Mike Spivey
