.\" Copyright (C) 1999\-2016 J. M. Spivey
.TH OBDB 1
.SH NAME
obdb \- Oberon\-2 debugger
.SH SYNOPSIS
.B obdb
[\-I
.IR DIR ]...
.I PROGRAM
.RI [ ARG ...]
.SH DESCRIPTION
.LP
.B Obdb
is a debugger associated with the Oxford Oberon compiler.
It starts the Oberon\-2 program
specified on the command line, passing to it any arguments specified,
and allows execution of the program to be observed and controlled from a graphical interface.
.TP
.BI -I DIR
add DIR to the list of directories to be searched.

.SH AUTHOR
Mike Spivey
