.\" Copyright (C) 1999 J. M. Spivey
.TH OBDUMP 1
.SH NAME
obdump \- Oberon\-2 line-count profiler
.SH SYNOPSIS
.B obdump
.I file
.SH DESCRIPTION
.B Obdump
reads the file
.I obprof.out
of line-count data written by
.B obprof
and correlates it with the source file specified on the command line.
The output is a listing of the source file with the line-counts shown
in the left margin.
.SH FILES
obdump.out \- line-count data
.SH AUTHOR
Mike Spivey
