#!/bin/sh

# How to make release 2.9.3:
#	Update release number in configure.in
#	Run all the tests: regress bigtest edtest errtest
#	run 'mkdist rel-2.9'

if [ $# -lt 1 ]; then
    echo 'Usage: mkdist release-branch [repository]'
    echo '       e.g. mkdist rel-2.9 ~/src/obc'
    exit 1
fi

set -x

RELEASE=$1
REPOS=${2:-~/src/obc}

VERSION=`hg cat -R $REPOS -r $RELEASE $REPOS/configure.in | 
    sed -n '/AC_INIT(obc, *\([0-9.]*\),.*/s//\1/p'`

if [ $VERSION = "" ]; then echo Oops!; exit 1; fi

echo "Located release $VERSION"

hg clone -r $RELEASE $REPOS obc-$VERSION

NODE=`sed -n '/^node: \(............\).*/s//\1/p' obc-$VERSION/.hg_archival.txt`

echo "Fetched node $NODE"

(cd obc-$VERSION \
    && sh scripts/debbuild \
    && ./configure \
    && make \
    && make bindist BINDIST=../obc-linux-$VERSION \
    && make distclean \
    && rm -rf .hg scripts/myconf
) || exit 1

tar cvfz obc-$VERSION.tar.gz obc-$VERSION || exit 1
tar cvfz obc-linux-$VERSION.tar.gz obc-linux-$VERSION || exit 1

