#!/bin/sh

for d in . ..; do
    if [ -r $d/configure.in ]; then
	srcdir=$d; break
    fi
done

if [ ! -r $srcdir/configure.in ]; then
    echo Couldn\'t find configure.in >&2
    exit 1
fi

(cd $srcdir && sh scripts/myauto)

$srcdir/configure --enable-debug "$@"
